//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public string MaBlog { get; set; }
        public string AnhBlog { get; set; }
        public string TieuDe { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string NgPost { get; set; }
        public string NoiDung { get; set; }
        public string AnhBlog_nho { get; set; }
    }
}
