//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTy
    {
        public string TenCty { get; set; }
        public string DiaChiCty { get; set; }
        public string SdtCty { get; set; }
    }
}
