//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public string MaNgayThang { get; set; }
        public Nullable<double> DoanhThu1 { get; set; }
        public Nullable<int> TongSLBanDc { get; set; }
        public string TenNhanVien { get; set; }
        public Nullable<int> SoDonBan { get; set; }
        public Nullable<double> DoanhThuNV { get; set; }
        public string TenSpBanChay { get; set; }
        public Nullable<int> SLBan { get; set; }
    }
}
