//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public double GiaBan { get; set; }
        public string Loai { get; set; }
        public string TinhTrang { get; set; }
        public string Anh { get; set; }
        public string GioiTinh { get; set; }
        public string MoTa { get; set; }
        public string Anh_hover { get; set; }
    
        public virtual GioiTinh GioiTinh1 { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
